### ISSUE TITLE
Send Message

### ISSUE THREAD

**Issue by claykoh** [unRob/CouchSurfing-API#4]
Hey -- awesome work! This should make surfing much easier!

Any idea how to send messages using the CS api?

I'd like to do a search and automatically hit up hosts that meet my criteria.

Thanks!

**Comment by unRob** [comment]
Thanks for your comments Clay.

I do have a vague idea, did you read the [example](https://github.com/unRob/CouchSurfing-API/blob/master/examples/example.rb)? Have a look at the notes in the [README](https://github.com/unRob/CouchSurfing-API/blob/master/README.md) as well.

**Comment by claykoh** [comment]
Hey Rob,

I read the example and the readme, but I don't see anything about sending messages. I see there's something about sending hosting requests, but I'd like to send a message automatically then manually make a hosting request if someone responds. ( although on the hosting request endpoint there's no way to send it to specific people yet right?

Is there something I'm missing? Are you suggesting that I try and reverse engineer that request myself?

Sorry to be a pain. I'm usually more of a python guy so I'll be learning ruby at the same time while doing this.

Thanks a lot!

**Comment by unRob** [comment]
I misread your message, sorry! No pain at all, just not a great deal of internet connectivity where I'm right now. The feature you mention is not implemented, a patch would be most welcome. This probably was my first public ruby project, I know the feeling.

I've kind of abandoned this project for a while, will try to update it and reverse engineer the API from the mobile clients when I return home. In the meantime, I'd really appreciate if you could submit a patch! There's some info on how I did some of the reverse engineering [here](https://github.com/unRob/CouchSurfing-API/pull/2#issuecomment-16404056).
